apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollout-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc            # value from argocd cluster list command
  project: default
  source:
    helm:      #this section is to override the release name, if not specified then metadata.name will be used during deploymen
      releaseName: rollout-app
      valueFiles:
      - ../../app/dev/service/demo/custom-values.yaml # custom values file in a diff directory
    path: argocd-and-argo-rollouts/helm/rollout-setweight               # where your helm chart exists
    repoURL: https://github.com/naavveenn/argocd.git  # URL for git repo
    targetRevision: main                              # branch name or tag name or commit id
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true
