apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Release.Name }}
spec:
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 50
      - pause: { duration: 1m }  
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "rollouts-setweight.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rollouts-setweight.labels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.container.name }}
        image: {{ .Values.image.repository }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: html_name
          value: "{{ .Values.container.env.html_name }}"
        ports:
        - containerPort: {{ .Values.container.port }}

